name: secondbrain_flutter
description: A local-first, encrypted task manager with intelligent scheduling algorithms
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_slider_drawer: ^2.1.1
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Date/Time
  intl: ^0.19.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Icons
  lucide_icons: 0.257.0
  
  # Encryption (for future use)
  crypto: ^3.0.3
  
  # Utilities
  uuid: ^4.2.1
  collection: ^1.17.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
